apiVersion: v1
kind: Service
metadata:
  name: redis-db
  labels:
    app: redis
    role: master
    tier: db
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
    tier: db