// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/number.proto

package number

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParityClient is the client API for Parity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParityClient interface {
	CheckParity(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberResponse, error)
}

type parityClient struct {
	cc grpc.ClientConnInterface
}

func NewParityClient(cc grpc.ClientConnInterface) ParityClient {
	return &parityClient{cc}
}

func (c *parityClient) CheckParity(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberResponse, error) {
	out := new(NumberResponse)
	err := c.cc.Invoke(ctx, "/Parity/CheckParity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParityServer is the server API for Parity service.
// All implementations must embed UnimplementedParityServer
// for forward compatibility
type ParityServer interface {
	CheckParity(context.Context, *NumberRequest) (*NumberResponse, error)
	mustEmbedUnimplementedParityServer()
}

// UnimplementedParityServer must be embedded to have forward compatible implementations.
type UnimplementedParityServer struct {
}

func (UnimplementedParityServer) CheckParity(context.Context, *NumberRequest) (*NumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckParity not implemented")
}
func (UnimplementedParityServer) mustEmbedUnimplementedParityServer() {}

// UnsafeParityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParityServer will
// result in compilation errors.
type UnsafeParityServer interface {
	mustEmbedUnimplementedParityServer()
}

func RegisterParityServer(s grpc.ServiceRegistrar, srv ParityServer) {
	s.RegisterService(&Parity_ServiceDesc, srv)
}

func _Parity_CheckParity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParityServer).CheckParity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Parity/CheckParity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParityServer).CheckParity(ctx, req.(*NumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Parity_ServiceDesc is the grpc.ServiceDesc for Parity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Parity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Parity",
	HandlerType: (*ParityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckParity",
			Handler:    _Parity_CheckParity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/number.proto",
}
