// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/number.proto

package number

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberResponse_RESULT int32

const (
	NumberResponse_PAIR   NumberResponse_RESULT = 0
	NumberResponse_IMPAIR NumberResponse_RESULT = 1
)

// Enum value maps for NumberResponse_RESULT.
var (
	NumberResponse_RESULT_name = map[int32]string{
		0: "PAIR",
		1: "IMPAIR",
	}
	NumberResponse_RESULT_value = map[string]int32{
		"PAIR":   0,
		"IMPAIR": 1,
	}
)

func (x NumberResponse_RESULT) Enum() *NumberResponse_RESULT {
	p := new(NumberResponse_RESULT)
	*p = x
	return p
}

func (x NumberResponse_RESULT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumberResponse_RESULT) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_number_proto_enumTypes[0].Descriptor()
}

func (NumberResponse_RESULT) Type() protoreflect.EnumType {
	return &file_proto_number_proto_enumTypes[0]
}

func (x NumberResponse_RESULT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumberResponse_RESULT.Descriptor instead.
func (NumberResponse_RESULT) EnumDescriptor() ([]byte, []int) {
	return file_proto_number_proto_rawDescGZIP(), []int{1, 0}
}

type NumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file_proto_number_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type NumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response NumberResponse_RESULT `protobuf:"varint,1,opt,name=response,proto3,enum=NumberResponse_RESULT" json:"response,omitempty"`
}

func (x *NumberResponse) Reset() {
	*x = NumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_number_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberResponse) ProtoMessage() {}

func (x *NumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_number_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberResponse.ProtoReflect.Descriptor instead.
func (*NumberResponse) Descriptor() ([]byte, []int) {
	return file_proto_number_proto_rawDescGZIP(), []int{1}
}

func (x *NumberResponse) GetResponse() NumberResponse_RESULT {
	if x != nil {
		return x.Response
	}
	return NumberResponse_PAIR
}

var File_proto_number_proto protoreflect.FileDescriptor

var file_proto_number_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x64, 0x0a,
	0x0e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x12, 0x08, 0x0a,
	0x04, 0x50, 0x41, 0x49, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4d, 0x50, 0x41, 0x49,
	0x52, 0x10, 0x01, 0x32, 0x3a, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x30, 0x0a,
	0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x2e, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_number_proto_rawDescOnce sync.Once
	file_proto_number_proto_rawDescData = file_proto_number_proto_rawDesc
)

func file_proto_number_proto_rawDescGZIP() []byte {
	file_proto_number_proto_rawDescOnce.Do(func() {
		file_proto_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_number_proto_rawDescData)
	})
	return file_proto_number_proto_rawDescData
}

var file_proto_number_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_number_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_number_proto_goTypes = []interface{}{
	(NumberResponse_RESULT)(0), // 0: NumberResponse.RESULT
	(*NumberRequest)(nil),      // 1: NumberRequest
	(*NumberResponse)(nil),     // 2: NumberResponse
}
var file_proto_number_proto_depIdxs = []int32{
	0, // 0: NumberResponse.response:type_name -> NumberResponse.RESULT
	1, // 1: Parity.CheckParity:input_type -> NumberRequest
	2, // 2: Parity.CheckParity:output_type -> NumberResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_number_proto_init() }
func file_proto_number_proto_init() {
	if File_proto_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_number_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_number_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_number_proto_goTypes,
		DependencyIndexes: file_proto_number_proto_depIdxs,
		EnumInfos:         file_proto_number_proto_enumTypes,
		MessageInfos:      file_proto_number_proto_msgTypes,
	}.Build()
	File_proto_number_proto = out.File
	file_proto_number_proto_rawDesc = nil
	file_proto_number_proto_goTypes = nil
	file_proto_number_proto_depIdxs = nil
}
